// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcv81BJNQq5W3_PMeACapTf6Jp_ZiMxo',
    appId: '1:229362814504:web:9c3543c46c4ce471e72f1d',
    messagingSenderId: '229362814504',
    projectId: 'my-note-plus-c1e09',
    authDomain: 'my-note-plus-c1e09.firebaseapp.com',
    storageBucket: 'my-note-plus-c1e09.firebasestorage.app',
    measurementId: 'G-7CJPZH7K7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPD3Bm14WHrbKxL8ianEEQRq7_h_fnkUQ',
    appId: '1:229362814504:android:c611dd0eba3235c0e72f1d',
    messagingSenderId: '229362814504',
    projectId: 'my-note-plus-c1e09',
    storageBucket: 'my-note-plus-c1e09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf5C7TieKWI7C25X9TzilHIjJ04D5wTC0',
    appId: '1:229362814504:ios:7fb711941eeaba3be72f1d',
    messagingSenderId: '229362814504',
    projectId: 'my-note-plus-c1e09',
    storageBucket: 'my-note-plus-c1e09.firebasestorage.app',
    iosBundleId: 'com.example.mynoteplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf5C7TieKWI7C25X9TzilHIjJ04D5wTC0',
    appId: '1:229362814504:ios:7fb711941eeaba3be72f1d',
    messagingSenderId: '229362814504',
    projectId: 'my-note-plus-c1e09',
    storageBucket: 'my-note-plus-c1e09.firebasestorage.app',
    iosBundleId: 'com.example.mynoteplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHcv81BJNQq5W3_PMeACapTf6Jp_ZiMxo',
    appId: '1:229362814504:web:bf7ead36c51daab6e72f1d',
    messagingSenderId: '229362814504',
    projectId: 'my-note-plus-c1e09',
    authDomain: 'my-note-plus-c1e09.firebaseapp.com',
    storageBucket: 'my-note-plus-c1e09.firebasestorage.app',
    measurementId: 'G-YS86GDSQJL',
  );
}
